apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: ${AIVEN_PG_HOST}:${AIVEN_PG_PORT}
    database: ${AIVEN_PG_DATABASE}
    user: ${AIVEN_PG_USER}
    secureJsonData:
      password: ${AIVEN_PG_PASSWORD}
    jsonData:
      sslmode: ${AIVEN_PG_SSL_MODE}
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    url: http://backend:8000/metrics
    access: proxy
    isDefault: false
    editable: true